---
redis:
  username:
  password:
  server: "redis:6379"
  database: "0"
  pool: "30"
  process: "1"
plugins:
  webhooks:
    workers: 1
    service_address: ":3002"
    github:
      path: "/github"
  codeflow:
    workers: 1
    dashboard_url: "https://example.com"
    logs_url: "https://example.com/##PROJECT-NAMESPACE##"
    jwt_secret_key:
    allowed_origins:
      - "http://localhost:3000"
      - "https://codeflow.checkrhq-dev.net"
      - "https://codeflow.checkrhq.net"
    default_service_spec:
      cpu: "500m"
      cpu_burst: "1000m"
      memory: "512Mi"
      memory_burst: "1Gi"
      termination_grace_period_seconds: 600
    mongodb:
      database: "codeflow"
      uri: "mongodb://mongo:27017"
      ssl: false
    service_address: ":3001"
    builds:
      path: "/builds"
    projects:
      path: "/projects"
    auth:
      path: "/oauth2"
      okta_org: ""
    users:
      path: "/users"
    features:
      path: "/features"
    websockets:
      path: "/ws"
    bookmarks:
      path: "/bookmarks"
    stats:
      path: "/stats"
  docker_build:
    workers: 1
    registry_host: "docker.io"
    registry_username: ""
    registry_password: ""
    registry_user_email: ""
    build_path: "/tmp"
    docker_host: "unix:///var/run/docker.sock"
  kubedeploy:
    workers: 1
  websockets:
    workers: 1
    service_address: ":3003"
  slack:
    workers: 1
    webhook_url: ""
