---
environment: "development"
redis:
  username:
  password:
  server: "redis:6379"
  database: "0"
  pool: "30"
  process: "1"
plugins:
  webhooks:
    workers: 1
    service_address: ":3002"
    github:
      path: "/github"
  codeflow:
    workers: 1
    dashboard_url: "https://codeflow.example.com"
    logs_url: "https://example.com/##PROJECT-NAMESPACE##"
    feature_external_link: "https://github.com/##PROJECT_REPOSITORY##/commit/##FEATURE-HASH##"
    jwt_secret_key: "change-me"
    allowed_origins:
      - "https://codeflow.checkrhq-dev.net"
      - "https://codeflow.checkrhq.net"
    default_service_spec:
      cpu: "500m"
      cpu_burst: "1000m"
      memory: "512Mi"
      memory_burst: "1Gi"
      termination_grace_period_seconds: 600
    mongodb:
      database: "codeflow"
      uri: "mongodb://mongo:27017"
      ssl: false
      connection_timeout: 3
      health_check_interval: 10
    service_address: ":3001"
    builds:
      path: "/builds"
    projects:
      path: "/projects"
    auth:
      path: "/auth"
      handler: "demo"
      okta_org: ""
      admin_groups:
        - admins
      engineer_groups:
        - engineering
    users:
      path: "/users"
    features:
      path: "/features"
    websockets:
      path: "/ws"
    bookmarks:
      path: "/bookmarks"
    stats:
      path: "/stats"
    admin:
      path: "/admin"
  docker_build:
    workers: 1
    registry_host: "docker.io"
    registry_org: ""
    registry_username: ""
    registry_password: ""
    registry_user_email: ""
    docker_host: "unix:///var/run/docker.sock"
    workdir: "/tmp/docker_build"   
  kubedeploy:
    workers: 1
    kubeconfig:
    environment: 
    ssl_cert_arn:
    node_selector: 
    access_log_s3_bucket: 
  websockets:
    workers: 1
    service_address: ":3003"
  slack:
    workers: 1
    webhook_url: ""
  git_sync:
    workers: 1
    workdir: "/tmp/git_sync" 
  heartbeat:
    workers: 1
  route53:
    workers: 0
    initial_wait_seconds: 300
    dns_resolve_timeout_seconds: 600
    aws_access_key_id: ""
    aws_secret_key: ""
    hosted_zone_id: ""
    hosted_zone_name: ""
